ScriptSim:
  ros__parameters:
    points:   
      # [moving_type, x, y, w] - moving_type: path, dock, or wait(x for seconds)
      - [path, 2.5, 1.3, 1.0]
      - [path, 2.6, 1.3, 1.0]
      - [path, 2.5, 0.4, 1.0]
      - [path, 2.6, 0.4, 1.0]
      - [wait, 5.0, 0.0, 0.0]
      - [path, 2.5, 0.4, 1.0]
      - [path, 2.6, 0.4, 1.0]
      - [path, 2.5, 0.4, 1.0]
      - [path, 2.6, 0.9, 1.0]
      - [path, 2.5, 0.9, 1.0]
      - [path, 2.6, 0.9, 1.0]
      - [dock, 1.5, 1.0, 1.0]
      