ScriptSim:
  ros__parameters:
    points:   
      # [moving_type, x, y, w] - moving_type: path, dock, or wait(x for seconds)
      # TODO: Fix the dock
      - [path, 1.5, 1.0, 1.0]
      - [wait, 1.0, 0.0, 0.0]
      - [path, 1.0, 1.0, 1.0]
      - [wait, 1.0, 0.0, 0.0]
      - [path, 1.0, 0.5, 1.0]
      - [wait, 1.0, 0.0, 0.0]
      - [path, 1.5, 0.5, 1.0]
      - [wait, 1.0, 0.0, 0.0]
      - [path, 1.5, 1.0, 1.0]
      